name: Publish CI
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: 'Next Version'
        required: true
        default: 'CURRENT'
      tags:
        description: 'Run publish to Maven Central and tagging'
env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail"
jobs:
  build:
    name: Publish task
    runs-on: ubuntu-latest
      timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          versionSnapshot=`grep 'projectVersion=' gradle.properties | sed 's/projectVersion=\([^-]*\)/\1/'`
      
